### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by dgeastman** [dgeastman/RangeSafety#1]
Here is the list of known issues and requests:

- [x] Finish configuring launch sites
- [x] Better handling of east/west inclination, especially if any launch sites have both
- [x] Destroy solids rather than letting them burn out
- [ ] "Stage to x" action
- [ ] Revert to nominal from arm if condition warrants?
- [ ] On screen alert messages
- [ ] Abort and destruct buttons
- [ ] Multiple corridors per range
- [ ] Destroy nearby parts after staging/abort
- [ ] Make parts explode instead of die
- [ ] Auto-disable final destruction of active vessel if crew are present
- [ ] Draw corridors in map view
